### ISSUE TITLE
How can I change the font size in the panel?

### ISSUE THREAD

**Issue by epsitec** [wallabyjs/public#369]
I am working on a high-DPI display and the messages in the panel are barely legible.
What CSS attributes do I have to tweak in order to increase the font size?

![wallaby-3](https://cloud.githubusercontent.com/assets/3872435/11552209/4b49b36e-9982-11e5-9221-423ea0d74854.png)

**Comment by ArtemGovorov** [comment]
In your styles.less file, add:
```LESS
.wallaby-panel-view .wallaby-panel-view-container .wallaby-panel-view-content {
  font-size: ...;
}
```

It's actually pretty easy to find out how style whatever you need in Atom:

![s](https://cloud.githubusercontent.com/assets/979966/11552401/e43786c6-99cf-11e5-9a35-f47dcc766e8b.gif)
